### ISSUE TITLE
silkworm_capi_test crashes with SILKWORM_SANITIZE on macOS

### ISSUE THREAD

**Issue by battlmonstr** [erigontech/silkworm#2108]
Using a Debug build on macOS 14.4.1 with:

```
-DCONAN_PROFILE=macos_arm64_clang_13_debug
-DSILKWORM_SANITIZE=address,undefined
```

Apple clang version 15.0.0 (clang-1500.3.9.4)
Xcode 15.3 

The crash happens after building `silkworm_capi_test` binary and running it:

    cmake --build build --target silkworm_capi_test -j6
    ./build/silkworm/capi/silkworm_capi_test

Crash details:

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==89455==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00010260f1f0 bp 0x00016d992740 sp 0x00016d992700 T0)
==89455==The signal is caused by a READ memory access.
==89455==Hint: address points to the zero page.
    #0 0x10260f1f0 in absl::lts_20230125::container_internal::GroupAArch64Impl::GroupAArch64Impl(absl::lts_20230125::container_internal::ctrl_t const*)+0x14 (silkworm_capi_test:arm64+0x1001a71f0)
    #1 0x1027b6aa8 in absl::lts_20230125::container_internal::FindInfo absl::lts_20230125::container_internal::find_first_non_full<void>(absl::lts_20230125::container_internal::CommonFields const&, unsigned long)+0x50 (silkworm_capi_test:arm64+0x10034eaa8)
    #2 0x126d1c8f4 in absl::lts_20230125::container_internal::raw_hash_set<absl::lts_20230125::container_internal::FlatHashMapPolicy<absl::lts_20230125::string_view, absl::lts_20230125::CommandLineFlag*>, absl::lts_20230125::container_internal::StringHash, absl::lts_20230125::container_internal::StringEq, std::__1::allocator<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>>::prepare_insert(unsigned long) raw_hash_set.h:2477
    #3 0x126d1bce4 in std::__1::pair<unsigned long, bool> absl::lts_20230125::container_internal::raw_hash_set<absl::lts_20230125::container_internal::FlatHashMapPolicy<absl::lts_20230125::string_view, absl::lts_20230125::CommandLineFlag*>, absl::lts_20230125::container_internal::StringHash, absl::lts_20230125::container_internal::StringEq, std::__1::allocator<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>>::find_or_prepare_insert<absl::lts_20230125::string_view>(absl::lts_20230125::string_view const&) raw_hash_set.h:2462
    #4 0x126d1ac20 in std::__1::pair<absl::lts_20230125::container_internal::raw_hash_set<absl::lts_20230125::container_internal::FlatHashMapPolicy<absl::lts_20230125::string_view, absl::lts_20230125::CommandLineFlag*>, absl::lts_20230125::container_internal::StringHash, absl::lts_20230125::container_internal::StringEq, std::__1::allocator<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>>::iterator, bool> absl::lts_20230125::container_internal::raw_hash_set<absl::lts_20230125::container_internal::FlatHashMapPolicy<absl::lts_20230125::string_view, absl::lts_20230125::CommandLineFlag*>, absl::lts_20230125::container_internal::StringHash, absl::lts_20230125::container_internal::StringEq, std::__1::allocator<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>>::EmplaceDecomposable::operator()<absl::lts_20230125::string_view, std::__1::piecewise_construct_t const&, std::__1::tuple<absl::lts_20230125::string_view const&&>, std::__1::tuple<absl::lts_20230125::CommandLineFlag*&&>>(absl::lts_20230125::string_view const&, std::__1::piecewise_construct_t const&, std::__1::tuple<absl::lts_20230125::string_view const&&>&&, std::__1::tuple<absl::lts_20230125::CommandLineFlag*&&>&&) const raw_hash_set.h:2262
    #5 0x126d1a594 in decltype(std::declval<absl::lts_20230125::container_internal::raw_hash_set<absl::lts_20230125::container_internal::FlatHashMapPolicy<absl::lts_20230125::string_view, absl::lts_20230125::CommandLineFlag*>, absl::lts_20230125::container_internal::StringHash, absl::lts_20230125::container_internal::StringEq, std::__1::allocator<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>>::EmplaceDecomposable>()(std::declval<absl::lts_20230125::string_view const&& const&>(), std::__1::piecewise_construct, std::declval<std::__1::tuple<absl::lts_20230125::string_view const&&>>(), std::declval<std::__1::tuple<absl::lts_20230125::CommandLineFlag*&&>>())) absl::lts_20230125::container_internal::memory_internal::DecomposePairImpl<absl::lts_20230125::container_internal::raw_hash_set<absl::lts_20230125::container_internal::FlatHashMapPolicy<absl::lts_20230125::string_view, absl::lts_20230125::CommandLineFlag*>, absl::lts_20230125::container_internal::StringHash, absl::lts_20230125::container_internal::StringEq, std::__1::allocator<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>>::EmplaceDecomposable, absl::lts_20230125::string_view const&&, std::__1::tuple<absl::lts_20230125::CommandLineFlag*&&>>(absl::lts_20230125::container_internal::raw_hash_set<absl::lts_20230125::container_internal::FlatHashMapPolicy<absl::lts_20230125::string_view, absl::lts_20230125::CommandLineFlag*>, absl::lts_20230125::container_internal::StringHash, absl::lts_20230125::container_internal::StringEq, std::__1::allocator<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>>::EmplaceDecomposable&&, std::__1::pair<std::__1::tuple<absl::lts_20230125::string_view const&&>, std::__1::tuple<absl::lts_20230125::CommandLineFlag*&&>>) container_memory.h:140
    #6 0x126d1a258 in decltype(memory_internal::DecomposePairImpl(std::forward<absl::lts_20230125::container_internal::raw_hash_set<absl::lts_20230125::container_internal::FlatHashMapPolicy<absl::lts_20230125::string_view, absl::lts_20230125::CommandLineFlag*>, absl::lts_20230125::container_internal::StringHash, absl::lts_20230125::container_internal::StringEq, std::__1::allocator<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>>::EmplaceDecomposable>(fp), PairArgs(std::forward<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>(fp0)))) absl::lts_20230125::container_internal::DecomposePair<absl::lts_20230125::container_internal::raw_hash_set<absl::lts_20230125::container_internal::FlatHashMapPolicy<absl::lts_20230125::string_view, absl::lts_20230125::CommandLineFlag*>, absl::lts_20230125::container_internal::StringHash, absl::lts_20230125::container_internal::StringEq, std::__1::allocator<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>>::EmplaceDecomposable, std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>(absl::lts_20230125::container_internal::raw_hash_set<absl::lts_20230125::container_internal::FlatHashMapPolicy<absl::lts_20230125::string_view, absl::lts_20230125::CommandLineFlag*>, absl::lts_20230125::container_internal::StringHash, absl::lts_20230125::container_internal::StringEq, std::__1::allocator<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>>::EmplaceDecomposable&&, std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>&&) container_memory.h:207
    #7 0x126d1a03c in decltype(absl::container_internal::DecomposePair(std::declval<absl::lts_20230125::container_internal::raw_hash_set<absl::lts_20230125::container_internal::FlatHashMapPolicy<absl::lts_20230125::string_view, absl::lts_20230125::CommandLineFlag*>, absl::lts_20230125::container_internal::StringHash, absl::lts_20230125::container_internal::StringEq, std::__1::allocator<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>>::EmplaceDecomposable>(), std::declval<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>())) absl::lts_20230125::container_internal::FlatHashMapPolicy<absl::lts_20230125::string_view, absl::lts_20230125::CommandLineFlag*>::apply<absl::lts_20230125::container_internal::raw_hash_set<absl::lts_20230125::container_internal::FlatHashMapPolicy<absl::lts_20230125::string_view, absl::lts_20230125::CommandLineFlag*>, absl::lts_20230125::container_internal::StringHash, absl::lts_20230125::container_internal::StringEq, std::__1::allocator<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>>::EmplaceDecomposable, std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>(absl::lts_20230125::container_internal::raw_hash_set<absl::lts_20230125::container_internal::FlatHashMapPolicy<absl::lts_20230125::string_view, absl::lts_20230125::CommandLineFlag*>, absl::lts_20230125::container_internal::StringHash, absl::lts_20230125::container_internal::StringEq, std::__1::allocator<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>>::EmplaceDecomposable&&, std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>&&) flat_hash_map.h:587
    #8 0x126d19f80 in decltype(absl::lts_20230125::container_internal::FlatHashMapPolicy<absl::lts_20230125::string_view, absl::lts_20230125::CommandLineFlag*>::apply(std::forward<absl::lts_20230125::container_internal::raw_hash_set<absl::lts_20230125::container_internal::FlatHashMapPolicy<absl::lts_20230125::string_view, absl::lts_20230125::CommandLineFlag*>, absl::lts_20230125::container_internal::StringHash, absl::lts_20230125::container_internal::StringEq, std::__1::allocator<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>>::EmplaceDecomposable>(fp), std::forward<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>(fp0))) absl::lts_20230125::container_internal::hash_policy_traits<absl::lts_20230125::container_internal::FlatHashMapPolicy<absl::lts_20230125::string_view, absl::lts_20230125::CommandLineFlag*>, void>::apply<absl::lts_20230125::container_internal::raw_hash_set<absl::lts_20230125::container_internal::FlatHashMapPolicy<absl::lts_20230125::string_view, absl::lts_20230125::CommandLineFlag*>, absl::lts_20230125::container_internal::StringHash, absl::lts_20230125::container_internal::StringEq, std::__1::allocator<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>>::EmplaceDecomposable, std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>, absl::lts_20230125::container_internal::FlatHashMapPolicy<absl::lts_20230125::string_view, absl::lts_20230125::CommandLineFlag*>>(absl::lts_20230125::container_internal::raw_hash_set<absl::lts_20230125::container_internal::FlatHashMapPolicy<absl::lts_20230125::string_view, absl::lts_20230125::CommandLineFlag*>, absl::lts_20230125::container_internal::StringHash, absl::lts_20230125::container_internal::StringEq, std::__1::allocator<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>>::EmplaceDecomposable&&, std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>&&) hash_policy_traits.h:134
    #9 0x126d19e28 in std::__1::pair<absl::lts_20230125::container_internal::raw_hash_set<absl::lts_20230125::container_internal::FlatHashMapPolicy<absl::lts_20230125::string_view, absl::lts_20230125::CommandLineFlag*>, absl::lts_20230125::container_internal::StringHash, absl::lts_20230125::container_internal::StringEq, std::__1::allocator<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>>::iterator, bool> absl::lts_20230125::container_internal::raw_hash_set<absl::lts_20230125::container_internal::FlatHashMapPolicy<absl::lts_20230125::string_view, absl::lts_20230125::CommandLineFlag*>, absl::lts_20230125::container_internal::StringHash, absl::lts_20230125::container_internal::StringEq, std::__1::allocator<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>>::emplace<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>, 0>(std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>&&) raw_hash_set.h:1886
    #10 0x126cf2a34 in std::__1::pair<absl::lts_20230125::container_internal::raw_hash_set<absl::lts_20230125::container_internal::FlatHashMapPolicy<absl::lts_20230125::string_view, absl::lts_20230125::CommandLineFlag*>, absl::lts_20230125::container_internal::StringHash, absl::lts_20230125::container_internal::StringEq, std::__1::allocator<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>>::iterator, bool> absl::lts_20230125::container_internal::raw_hash_set<absl::lts_20230125::container_internal::FlatHashMapPolicy<absl::lts_20230125::string_view, absl::lts_20230125::CommandLineFlag*>, absl::lts_20230125::container_internal::StringHash, absl::lts_20230125::container_internal::StringEq, std::__1::allocator<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>>>::insert<std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>, 0, std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>, 0, (std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>*)0>(std::__1::pair<absl::lts_20230125::string_view const, absl::lts_20230125::CommandLineFlag*>&&) raw_hash_set.h:1784
    #11 0x126cef318 in absl::lts_20230125::flags_internal::FlagRegistry::RegisterFlag(absl::lts_20230125::CommandLineFlag&, char const*) reflection.cc:130
    #12 0x126cf5a14 in absl::lts_20230125::flags_internal::RegisterCommandLineFlag(absl::lts_20230125::CommandLineFlag&, char const*) reflection.cc:192
    #13 0x126c806f0 in absl::lts_20230125::flags_internal::FlagRegistrar<absl::lts_20230125::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>::FlagRegistrar(absl::lts_20230125::flags_internal::Flag<absl::lts_20230125::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>&, char const*) flag.h:779
    #14 0x126c74548 in absl::lts_20230125::flags_internal::FlagRegistrar<absl::lts_20230125::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>::FlagRegistrar(absl::lts_20230125::flags_internal::Flag<absl::lts_20230125::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>&, char const*) flag.h:777
    #15 0x126c875e0 in __cxx_global_var_init+0x130 (libsilkworm_capi.dylib:arm64+0x75475e0)
    #16 0x126c88d58 in _GLOBAL__sub_I_config_vars.cc+0x14 (libsilkworm_capi.dylib:arm64+0x7548d58)
    #17 0x183009058 in invocation function for block in dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const::$_0::operator()() const+0xa4 (dyld:arm64e+0xfffffffffff69058)
    #18 0x183047304 in invocation function for block in dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const+0x150 (dyld:arm64e+0xfffffffffffa7304)
    #19 0x18303a998 in invocation function for block in dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const+0x1ec (dyld:arm64e+0xfffffffffff9a998)
    #20 0x182fea2f8  (<unknown module>)
    #21 0x18303992c in dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const+0xbc (dyld:arm64e+0xfffffffffff9992c)
    #22 0x183046e18 in dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const+0x200 (dyld:arm64e+0xfffffffffffa6e18)
    #23 0x18300506c  (<unknown module>)
    #24 0x18300b610 in dyld4::JustInTimeLoader::runInitializers(dyld4::RuntimeState&) const+0x20 (dyld:arm64e+0xfffffffffff6b610)
    #25 0x183005458  (<unknown module>)
    #26 0x1830053fc  (<unknown module>)
    #27 0x1830090e8 in dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const::$_1::operator()() const+0x70 (dyld:arm64e+0xfffffffffff690e8)
    #28 0x183005624  (<unknown module>)
    #29 0x1830284d4 in dyld4::APIs::runAllInitializersForMain()+0x1cc (dyld:arm64e+0xfffffffffff884d4)
    #30 0x182feef78  (<unknown module>)
    #31 0x182feded8  (<unknown module>)

```

It happens before any test runs when it tries to initialize some static data within the absl command line flags library ( flags_internal::FlagRegistrar / flags_internal::FlagRegistry ).

**Comment by battlmonstr** [comment]
fixed by [#2570](https://github.com/erigontech/silkworm/pull/2570) and https://github.com/erigontech/silkworm/pull/2576
