### ISSUE TITLE
rpcdaemon: intermittent failures in E3 RPC integration tests via gRPC

### ISSUE THREAD

**Issue by canepat** [erigontech/silkworm#2464]
RPC integration tests against E3 fail intermittently often (even if not always) because of `rpcdaemon` unexpected termination:

https://github.com/erigontech/silkworm/actions/runs/11576758305/job/32227046300?pr=2463

This started to happen after switching to usage of gRPC for remote RPC integration testing with E3, so It could  be related to some data race due to gRPC API misuse (just speculation).

**Comment by canepat** [comment]
After some RPC stress testing on our self-hosted runner, it became evident that there is no unexpected termination of `rpcdaemon` (even if `rpc-tests` logs may be misleading). These failures turned out to be caused by a crash in E3 alpha5:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x22e4b2a]

goroutine 5213779 [running]:
github.com/erigontech/erigon/turbo/execution/eth1.(*EthereumExecutionModule).updateForkChoice.func1({0x34aee90, 0xc31e6d2c80})
  github.com/erigontech/erigon/turbo/execution/eth1/forkchoice.go:204 +0x8a
github.com/erigontech/erigon-lib/kv/temporal.(*DB).Update(0x9eaec8d246998270?, {0x3475f68?, 0xc0011ce5f0?}, 0xc31e6d2c40)
  github.com/erigontech/erigon-lib@v0.0.0-00010101000000-000000000000/kv/temporal/kv_temporal.go:125 +0x96
github.com/erigontech/erigon/turbo/execution/eth1.(*EthereumExecutionModule).updateForkChoice(0xc17f429b80, {0x3475f68, 0xc0011ce5f0}, {0xd0, 0xee, 0x58, 0xd6, 0xde, 0xb8, 0xec, ...}, ...)
  github.com/erigontech/erigon/turbo/execution/eth1/forkchoice.go:199 +0x1cc
created by github.com/erigontech/erigon/turbo/execution/eth1.(*EthereumExecutionModule).UpdateForkChoice in goroutine 5210273
  github.com/erigontech/erigon/turbo/execution/eth1/forkchoice.go:130 +0x329
```
This has been solved [here](https://github.com/erigontech/erigon/pull/12377), so we upgraded E3 to the target commit on our self-hosted runner and all is good again.
